# -*- coding: utf-8 -*-
"""ShAI_BootCamp_Assignment (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SjNtzLnQPQzSFRMlSxSHruCME9dBVRRs

#About Dataset
salaries dataset generally provides information about the employees of an organization in relation to their compensation. It typically includes details such as how much each employee is paid (their salary), their job titles, the departments they work in, and possibly additional information like their level of experience, education, and employment history within the organization.

# Features
- 'Id'
- 'EmployeeName'
- 'JobTitle'
- 'BasePay'
- 'OvertimePay'
- 'OtherPay'
- 'Benefits'
- 'TotalPay' -> salary
- 'TotalPayBenefits'
- 'Year'
- 'Notes'
- 'Agency'
- 'Status'

# Tasks

1. **Basic Data Exploration**: Identify the number of rows and columns in the dataset, determine the data types of each column, and check for missing values in each column.

2. **Descriptive Statistics**: Calculate basic statistics mean, median, mode, minimum, and maximum salary, determine the range of salaries, and find the standard deviation.

3. **Data Cleaning**: Handle missing data by suitable method with explain why you use it.

4. **Basic Data Visualization**: Create histograms or bar charts to visualize the distribution of salaries, and use pie charts to represent the proportion of employees in different departments.

5. **Grouped Analysis**: Group the data by one or more columns and calculate summary statistics for each group, and compare the average salaries across different groups.

6. **Simple Correlation Analysis**: Identify any correlation between salary and another numerical column, and plot a scatter plot to visualize the relationship.

8. **Summary of Insights**: Write a brief report summarizing the findings and insights from the analyses.

# Very Important Note
There is no fixed or singular solution for this assignment, so if anything is not clear, please do what you understand and provide an explanation.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load your dataset
df = pd.read_csv('/content/salary.csv')
df.head()

df.columns

df.shape

df.dtypes

df.isnull()

df.describe()

df['Benefits'].fillna('unknown',inplace=True)
df
#قمنا بتحديد قيم العمود Benefits
# كقيم مفقودة ثم استخدمنا التعليمة fillna()
#لتعويض القيم المفقودة بقيمة معينة

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
plt.hist(df['TotalPay'], bins=20, color='skyblue')
plt.title('salaries')
plt.xlabel('salary')
plt.ylabel('Employee')
plt.show()

department_counts = df['JobTitle'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(department_counts, labels=department_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('persentage of employees in different departments')
plt.show()

average_salary=df.groupby('JobTitle')['TotalPay'].mean()
average_salary

correlation = df['TotalPay'].corr(df['TotalPayBenefits'])
print("Correlation between TotalPay and TotalPayBenefits:", correlation)
import matplotlib.pyplot as plt
plt.scatter(df['TotalPayBenefits'], df['TotalPay'])
plt.xlabel('TotalPayBenefits')
plt.ylabel('TotalPay')
plt.title('Scatter Plot of TotalPay vs TotalPayBenefits')
plt.show()

"""# Good Luck!"""